export const CUSTOMER_ADDED = "CUSTOMER_ADDED";
export const CUSTOMER_DELETED = "CUSTOMER_DELETED";
export const CUSTOMER_UPDATED = "CUSTOMER_UPDATED";
export const CUSTOMER_SELECTED = "CUSTOMER_SELECTED";

export const MESSAGE_ADDED = "MESSAGE_ADDED";

export const COMPETITION_ADDED = "COMPETITION_ADDED";
export const COMPETITION_DELETED = "COMPETITION_DELETED";
export const COMPETITION_UPDATED = "COMPETITION_UPDATED";
export const COMPETITION_SELECTED = "COMPETITION_SELECTED";

export const RECIPE_ADDED = "RECIPE_ADDED";
export const RECIPE_DELETED = "RECIPE_DELETED";
export const RECIPE_SELECTED = "RECIPE_SELECTED";
export const RECIPE_UPDATED = "RECIPE_UPDATED";

export const PRODUCT_SELECTED = "PRODUCT_SELECTED";
export const PRODUCT_ADDED = "PRODUCT_ADDED";
export const PRODUCT_DELETED = "PRODUCT_DELETED";
export const PRODUCT_UPDATED = "PRODUCT_UPDATED";
export const PRODUCTS_SAVED = "PRODUCTS_SAVED";

export const ORDER_ADDED = "ORDER_ADDED";
export const ORDER_SELECTED = "ORDER_SELECTED";
export const ORDER_DELETED = "ORDER_DELETED";
export const ORDER_UPDATED = "ORDER_UPDATED";

export const RECOMMENDED_PRODUCT_ADDED = "RECOMMENDED_PRODUCT_ADDED";
export const RECOMMENDED_PRODUCT_SELECTED = "RECOMMENDED_PRODUCT_SELECTED";
export const RECOMMENDED_PRODUCT_DELETED = "RECOMMENDED_PRODUCT_DELETED";
export const RECOMMENDED_PRODUCT_UPDATED = "RECOMMENDED_PRODUCT_UPDATED";
